version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: travel_db
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: omarsalem22/travel-backend:latest
    container_name: travel_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: CFlrMMoGpaR8qKtYTLvrHoRRhO583ZZwhrbr4gB7Bds=
      APP_JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travel_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
